import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Common/Header";

export const metadata: Metadata = {
  title: "게이시판",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Header />
        <main className="container mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
